version: 2
jobs:
  build:
    docker:
      - image: carlosesilva/wp-phpunit-xdebug
      - image: circleci/mysql:5.7
    working_directory: ~/repo
    steps:
      - checkout

      # # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "composer.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-
      # - run: composer install -n --prefer-dist
      # - save_cache:
      #     paths:
      #       - ./vendor
      #     key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-v0.6.0.tar.gz && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-v0.6.0.tar.gz && rm dockerize-alpine-linux-amd64-v0.6.0.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      # run setup!
      - run: bin/install-wp-tests.sh circle_test root '' localhost 4.9 true
      # run tests!
      - run: WP_MULTISITE=0 phpunit --exclude-group=ms-required
      - run: WP_MULTISITE=1 phpunit --exclude-group=ms-excluded
